### ISSUE TITLE
CircularProgressBar antialias

### ISSUE THREAD

**Issue by MarioLenci** [Sage42/AndroidViewUtils#4]
The Paint objects you use to draw things in CircularProgressBar should be with antialias

I did it like this:

// create paint settings based on supplied args
this.mBgPaint = new Paint();
this.mBgPaint.setColor(bgColor);
this.mBgPaint.setStyle(Style.STROKE);
this.mBgPaint.setAntiAlias(true);
this.mBgPaint.setStrokeWidth(bgStrokeWidth);

this.mProgressPaint = new Paint();
this.mProgressPaint.setColor(progressColor);
this.mProgressPaint.setStyle(Style.STROKE);
this.mProgressPaint.setAntiAlias(true);
this.mProgressPaint.setStrokeWidth(progressStrokeWidth);

this.mTextPaint = new Paint();
this.mTextPaint.setColor(textColor);
this.mTextPaint.setAntiAlias(true);
this.mTextPaint.setStyle(Style.STROKE);
this.mTextPaint.setTextAlign(Align.CENTER);
this.mTextPaint.setTextSize(textSize);

**Comment by corsc** [comment]
Thanks for the idea, i will try adding that setting when I have a chance.

**Comment by corsc** [comment]
Added suggested anti-aliasing
